name: Scala CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run linter
      run: sbt scalafix --check
    - name: Run tests
      run: sbt clean coverage test
    - name: Generate coverage report
      run: sbt coverageReport coveralls
    - name: Build docker
      run: sbt docker:publishLocal
